version: '3.7'

services:
  php:
    build:
      context: .docker/php
    volumes:
      - .:/var/www/html:cached
    ports:
      - "8000:80"
    environment:
      MYSQL_HOST: db
      MYSQL_VERSION: 8
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/mysql
  node:
    image: node:latest
    command: yarn watch
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  php-test:
    build:
      context: .docker/php
    volumes:
      - .:/var/www/html:cached
    environment:
      MYSQL_HOST: db-test
      MYSQL_VERSION: 8
      APP_ENV: test
    depends_on:
      - db-test
    command: php /var/www/html/bin/phpunit
  db-test:
    image: mysql:8
    env_file:
      - .env.test.local

volumes:
  db-data:
