version: '3.7'

services:
  php:
    build:
      context: .docker/php
    volumes:
      - .:/var/www/html:cached
    ports:
      - "8000:80"
    environment:
      MYSQL_HOST: db
      MYSQL_VERSION: 8
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
